import * as fs from "node:fs";
import * as path from "node:path";

export type ChartInput = {
  chartType: "bar" | "line" | "pie";
  title: string;
  data: Array<Record<string, unknown>>;
  xKey?: string;
  yKey?: string;
};

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function inlineEcharts(projectRoot: string): string {
  const candidates = [
    path.resolve(projectRoot, "node_modules", "echarts", "dist", "echarts.min.js"),
    path.resolve(projectRoot, "node_modules", "echarts", "dist", "echarts.js"),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return fs.readFileSync(p, "utf8");
  }
  throw new Error("ECharts not found in node_modules. Run npm install.");
}

function normalizeData(input: ChartInput): { labels: string[]; values: number[]; raw: Array<{ name: string; value: number }> } {
  if (!Array.isArray(input.data) || input.data.length === 0) throw new Error("data must be a non-empty array");
  const xKey = input.xKey ?? "name";
  const yKey = input.yKey ?? "value";
  const raw: Array<{ name: string; value: number }> = input.data.map((row, idx) => {
    const name = String((row as Record<string, unknown>)[xKey] ?? (row as Record<string, unknown>)["name"] ?? `Item ${idx + 1}`);
    const valRaw = (row as Record<string, unknown>)[yKey] ?? (row as Record<string, unknown>)["value"];
    const value = Number(valRaw);
    if (!Number.isFinite(value)) throw new Error(`Invalid numeric value at index ${idx}: ${String(valRaw)}`);
    return { name, value };
  });
  return { labels: raw.map((r) => r.name), values: raw.map((r) => r.value), raw };
}

export function buildChartHtml(input: ChartInput & { projectRoot: string }): string {
  const echartsJs = inlineEcharts(input.projectRoot);
  const { labels, values, raw } = normalizeData(input);
  const title = escapeHtml(input.title);

  let optionJs: string;
  if (input.chartType === "pie") {
    const dataJs = JSON.stringify(raw);
    optionJs = `{
      title: { text: ${JSON.stringify(title)}, left: 'center' },
      tooltip: { trigger: 'item' },
      legend: { bottom: 0 },
      series: [{ type: 'pie', radius: '62%', data: ${dataJs}, label: { formatter: '{b}: {c}' } }]
    }`;
  } else if (input.chartType === "line") {
    optionJs = `{
      title: { text: ${JSON.stringify(title)}, left: 'center' },
      tooltip: { trigger: 'axis' },
      xAxis: { type: 'category', data: ${JSON.stringify(labels)} },
      yAxis: { type: 'value' },
      series: [{ type: 'line', smooth: true, data: ${JSON.stringify(values)}, areaStyle: {} }]
    }`;
  } else {
    optionJs = `{
      title: { text: ${JSON.stringify(title)}, left: 'center' },
      tooltip: { trigger: 'axis' },
      xAxis: { type: 'category', data: ${JSON.stringify(labels)} },
      yAxis: { type: 'value' },
      series: [{ type: 'bar', data: ${JSON.stringify(values)}, itemStyle: { borderRadius: [6,6,0,0] } }]
    }`;
  }

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
  html, body { margin:0; padding:0; background:#f8fafc; color:#0f172a; font-family: ui-sans-system, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; }
  .wrap { max-width: 960px; margin: 24px auto; padding: 16px; }
  .card { background:#fff; border:1px solid #e2e8f0; border-radius:16px; padding:16px; box-shadow: 0 1px 2px rgba(15,23,42,.06); }
  h1 { font-size:18px; text-align:center; margin:0 0 12px; letter-spacing:-.01em; }
  #chart { width:100%; height:520px; }
  .caption { text-align:center; color:#64748b; font-size:12px; margin-top:8px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="card">
    <h1>${title}</h1>
    <div id="chart"></div>
    <div class="caption">Generated by OpenCode Visualize · ${title}</div>
  </div>
</div>
<script>${echartsJs}<\/script>
<script>
  const chart = echarts.init(document.getElementById('chart'));
  const option = ${optionJs};
  chart.setOption(option);
  window.addEventListener('resize', () => chart.resize());
<\/script>
</body>
</html>`;
}
